workflows:
  flutter-workflow:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_MODE: release
    scripts:
      - name: Build Android APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
